import { Routes } from '@angular/router';
import { CropDetailsComponent } from './features/crops/crop-details/crop-details.component';
import { CropListComponent } from './features/crops/crop-list/crop-list.component';
import { CropRegistrationComponent } from './features/crops/crop-registration/crop-registration.component';
import { EligibilityCheckComponent } from './features/eligibility/eligibility-check/eligibility-check.component';
import { EligibilityDetailsComponent } from './features/eligibility/eligibility-details/eligibility-details.component';
import { EligibilityListComponent } from './features/eligibility/eligibility-list/eligibility-list.component';
import { EnrollmentCreateComponent } from './features/enrollments/enrollment-create/enrollment-create.component';
import { EnrollmentDetailsComponent } from './features/enrollments/enrollment-details/enrollment-details.component';
import { EnrollmentListComponent } from './features/enrollments/enrollment-list/enrollment-list.component';
import { InventoryItemsComponent } from './features/inventory/inventory-items/inventory-items.component';
import { InventoryReservationDetailsComponent } from './features/inventory/inventory-reservation-details/inventory-reservation-details.component';
import { InventoryReservationListComponent } from './features/inventory/inventory-reservation-list/inventory-reservation-list.component';
import { InventoryReserveComponent } from './features/inventory/inventory-reserve/inventory-reserve.component';
import { FarmerDetailsComponent } from './features/farmers/farmer-details/farmer-details.component';
import { FarmerListComponent } from './features/farmers/farmer-list/farmer-list.component';
import { FarmerRegistrationComponent } from './features/farmers/farmer-registration/farmer-registration.component';
import { FarmDetailsComponent } from './features/farms/farm-details/farm-details.component';
import { FarmListComponent } from './features/farms/farm-list/farm-list.component';
import { FarmRegistrationComponent } from './features/farms/farm-registration/farm-registration.component';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'farmers' },
  { path: 'farmers', component: FarmerListComponent },
  { path: 'farmers/register', component: FarmerRegistrationComponent },
  { path: 'farmers/:id', component: FarmerDetailsComponent },
  { path: 'farms', component: FarmListComponent },
  { path: 'farms/register', component: FarmRegistrationComponent },
  { path: 'farms/:id', component: FarmDetailsComponent },
  { path: 'crops', component: CropListComponent },
  { path: 'crops/register', component: CropRegistrationComponent },
  { path: 'crops/:id', component: CropDetailsComponent },
  { path: 'eligibility', component: EligibilityListComponent },
  { path: 'eligibility/check', component: EligibilityCheckComponent },
  { path: 'eligibility/:id', component: EligibilityDetailsComponent },
  { path: 'enrollments', component: EnrollmentListComponent },
  { path: 'enrollments/create', component: EnrollmentCreateComponent },
  { path: 'enrollments/:id', component: EnrollmentDetailsComponent },
  { path: 'inventory/items', component: InventoryItemsComponent },
  { path: 'inventory/reserve', component: InventoryReserveComponent },
  { path: 'inventory/reservations', component: InventoryReservationListComponent },
  { path: 'inventory/reservations/:id', component: InventoryReservationDetailsComponent },
];
